image: node0.10
script:
  - ./test_drone.sh
  - nvm install 0.10.29
  - nvm use 0.10.29
env:
  - npmdeployusername={{npmdeployusername}}
  - npmdeploypassword={{npmdeploypassword}}
  - email={{email}}
notify:
  email:
    recipients:
      - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook 
publish:
  npm:
    email: {{email}}
    username: {{npmdeployusername}}
    password: {{npmdeploypassword}}
    branch: master
    registry: "https://clever.registry.nodejitsu.com"
