image: node0.10
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  npm:
    email: $$email
    password: $$npmdeploypassword
    username: $$npmdeployusername
    when:
      branch: master
script:
  - npm config set ca ""
  - npm install
  - nvm install 0.10.29
  - nvm use 0.10.29
  - make test
