image: clever/drone-node:6.2.2
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  npm:
    email: $$npm_drone_email
    password: $$npm_drone_password
    username: $$npm_drone_username
    when:
      branch: master
script:
- npm config set ca ""
- npm install
- make test
- nvm install 6
- nvm use 6

