version: 2
jobs:
  build:
    working_directory: ~/Clever/node-process-metrics
    docker:
    - image: circleci/node:14-stretch
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - run:
        command: npm install
        name: npm ci
    - run: make build
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/npm-publish $NPM_TOKEN .; fi;
